### ISSUE TITLE
After completing contract steps, plugin no longer puts an arrow above the "client's" head

### ISSUE THREAD

**Issue by hjdarnel** [TheStonedTurtle/Mahogany-Homes#1]
As always, thanks for the sick plugins.

This morning I was running some contracts and everything seems normal (arrow on map pointing to the house, highlighted objects to build) but after building each object, the guy that you talk to afterwards to finish and get the stamina tea isn't pointed to anymore.

Screenshot:
![Screenshot](https://user-images.githubusercontent.com/7868899/94712919-bde18b80-030f-11eb-87f7-9898631ebe37.png)

There was an update this morning that maybe borked it.

Cheers!

**Comment by TheStonedTurtle** [comment]
Does this happen to all NPCs or just Norman for you? I just tested this with `Tau` and it seems to be working as expected. 

![image](https://user-images.githubusercontent.com/29030969/94757621-9c07f900-034f-11eb-8a19-9b961ed1f504.png)

**Comment by hjdarnel** [comment]
For me, it happens with every contract npc. I did like 3 hours of contracts today and didn't see one that worked.

**Comment by hjdarnel** [comment]
Upon reloading, I'm not seeing a problem now. I did 2-3 hours this afternoon with the problem though. 🤷
