### ISSUE TITLE
Contract overlay doesn't clear

### ISSUE THREAD

**Issue by xSlysoft** [TheStonedTurtle/Mahogany-Homes#10]
Not sure what changed recently as I just noticed this today, but when completing a contract the overlay for that contract doesn't clear itself and continues to point towards the person you just finished, including flashing arrow over their head, until you go and get a new contract.

**Comment by TheStonedTurtle** [comment]
@xSlysoft Have you completed > 1000 contracts and/or have over 1000 points?

**Comment by IchottMano** [comment]
Hello!
I've been experiencing the same problem recently. I have completed around 1500 contracts.

**Comment by TheStonedTurtle** [comment]
This should have been fixed in 1c43b1805a6fd29030d1c9b6e3af3246ad683b78 as it now includes commas in the points and contracts regex matcher. If this error still persists after version 1.4 please open a new issue.

**Comment by xSlysoft** [comment]
Sorry I didn't get an email notification for your comment, no I did not have > 1000 contracts but I did have > 1000 points. However, the issue is fixed now on my end. Thanks.
