### ISSUE TITLE
Requesting longer or toggle-able timeout for overlay

### ISSUE THREAD

**Issue by shermaza** [TheStonedTurtle/Mahogany-Homes#14]
Hey there, thanks for the great plugin. I'd like to request an option to disable the overlay timeout, or maybe allow us to extend it. On a UIM, going back to Priff to get a new inventory of logs usually means I have gone past the timeout and I have to NPC contact again to get the overlay back.

**Comment by TheStonedTurtle** [comment]
Closes as done as there is a config option to set the timeout to up to 60 minutes
![image](https://user-images.githubusercontent.com/29030969/218287525-c5a34514-5436-476e-89e3-bb2900d94cfa.png)
