### ISSUE TITLE
Suggestion: highlight options

### ISSUE THREAD

**Issue by ArashiJoe** [TheStonedTurtle/Mahogany-Homes#16]
This plugin is simple but extremely effective--Thanks for making an awesome helper!

One thing I would love to see is the ability to customize how hotspots are highlighted --either "Tiles" or "Hull"--with additional options to select the border thickness, border color, and fill color of the overlayed highlights. Adding separate highlight options for stairs+ladders would be incredible too.

**Comment by Dennis-0** [comment]
This so much, I just started using the plugin, and the ability to change the highlight colours for stairs/ladders would be so useful, so I can stop going down a ladder thinking it's an object.
