### ISSUE TITLE
Plank counts are incorrect - new info available on the wiki

### ISSUE THREAD

**Issue by dolphinspired** [TheStonedTurtle/Mahogany-Homes#17]
I've been using your plugin to do Novice (Oak) contracts, and I noticed something was off about the estimated plank counts. So I did some digging and consulted with another developer on the wiki, and we confirmed that the information previously on the wiki was incomplete.

In short, there are only handful of possible hotspot layouts that you can receive for a given house, and those layouts are different per difficulty tier. Meaning that the number of planks you might need to complete a contract is **different depending on the tier of the contract**. The numbers previously in the wiki (and used in this plugin) seem to have been roughly based on the Adept (Teak) tier.

I've [updated the wiki](https://oldschool.runescape.wiki/w/Mahogany_Homes#Contract_locations) to include the actual plank count ranges for each house, separated by difficulty. I would love it if this plugin could check for the difficulty of a contract before showing a plank range. I've also included the %-chance that a contract will require a steel bar, could be helpful to include that info as well.

**Comment by TheStonedTurtle** [comment]
This was added in commit bf543bf63fb5a119d023a03e4f3f796df4c2d964
