### ISSUE TITLE
Plugin not loading with newest build of RL

### ISSUE THREAD

**Issue by AmericanGoku** [TheStonedTurtle/Mahogany-Homes#19]
Had the plugin last night but was removed from installed plugins and other users have reported same issu
![Screenshot 2022-07-13 124856](https://user-images.githubusercontent.com/80642525/178798092-b3278151-6c20-4466-99fc-0a47e49bea5e.png)
e

**Comment by josh1209** [comment]
Also having this issue as of today, July 13th, 2022

**Comment by TheStonedTurtle** [comment]
Plugin broke with recent RL changes, PR has been made and this should be resolved once it's merged.

https://github.com/runelite/plugin-hub/pull/3010
