### ISSUE TITLE
Add "Required Materials" to the infobox

### ISSUE THREAD

**Issue by vitorebom** [TheStonedTurtle/Mahogany-Homes#2]
Since the plugin can track which objects are marked to build, make it sum up the planks/bars needed for the currently active contract

**Comment by TheStonedTurtle** [comment]
Unfortunately the items to be marked only update when you are close to the house so this information wouldn't be very helpful.

**Comment by richardg93** [comment]
According to the wiki, the only materials that vary are for the potential repairs? I would find it very helpful if the overlay showed that this contract will require "11-12 planks", then it could change once its all been loaded.

**Comment by MirrorImageQS** [comment]
There's an alternative for this - once you're given your contract, there's a maximum amount of materials that you'll ever need for that person (the wiki lists those on the Mahogany Homes page - https://oldschool.runescape.wiki/w/Mahogany_Homes). You could report those maximum material numbers until you get close to the house, and then update once you're close enough.

That would also provide a starting point for having it change color to warn when you don't have enough materials on hand for the action.

**Comment by TheStonedTurtle** [comment]
This feature was added in #8, and while it doesn't update when you've reached the house or when you fix stuff within the house I believe it is good enough to close this issue. You can create another issue if you feel that tracking while inside the house is important.
