### ISSUE TITLE
bug: all tasks mark as complete after completing any one

### ISSUE THREAD

**Issue by Orimazer** [TheStonedTurtle/Mahogany-Homes#21]
after the most recent update, whenever one task is completed, all task highlighting is removed and the arrow to the owner is applied, despite other tasks still needing to be done. removing a piece of furnature will reapply all remaining highlights, but building the replacement will again cause this. 
![2022-07-14 04_59_34-RuneLite](https://user-images.githubusercontent.com/16553650/178895930-f63d2509-1cb6-4066-b7c0-dee6a2423678.png)
![2022-07-14 04_59_47-RuneLite](https://user-images.githubusercontent.com/16553650/178895750-16a6320a-f8e6-4abb-ba06-e68cbce3266f.png)
.

**Comment by TheStonedTurtle** [comment]
I am not able to replicate this, can you tell me what version of the plugin you are using? You should see the version in the plugin-hub panel.

![image](https://user-images.githubusercontent.com/29030969/178898469-f19ea213-4870-4a2f-befc-0ab27141f2af.png)

**Comment by Orimazer** [comment]
i am on 1.5 
![image](https://user-images.githubusercontent.com/16553650/178898815-2fa47001-712e-49f8-8502-2a448006aa9a.png)

**Comment by TheStonedTurtle** [comment]
I can't replicate this so I can't fix it, I don't know what to tell you.

I'm doing an `expert` contract at the same location as you and I don't see it.

![image](https://user-images.githubusercontent.com/29030969/178899440-ca8e34ed-8ede-4cc2-a698-e146cd7882c2.png)

![image](https://user-images.githubusercontent.com/29030969/178899504-8cd617b9-8c71-4d5d-945b-d5e8dd9be40a.png)

![image](https://user-images.githubusercontent.com/29030969/178899514-960377a0-35d0-464e-8fec-e97a0696b466.png)

**Comment by TheStonedTurtle** [comment]
The only other thing I can think of is maybe it's dependent on your config options for the plugin?

![image](https://user-images.githubusercontent.com/29030969/178899636-2e2bdcf4-03d6-4587-988a-4d62029337a3.png)

**Comment by Orimazer** [comment]
well i feel a little the fool, restarting fixed it. sorry for the wasted time, should definitely have done that first.

**Comment by TheStonedTurtle** [comment]
No worries, no idea how or why this would have happened to you though.
