### ISSUE TITLE
Feature Request : Session Timeout/Planksack

### ISSUE THREAD

**Issue by PJGJ210** [TheStonedTurtle/Mahogany-Homes#24]
Came here as I would afk and timeout. I have found the timeout config option but thinking a toggle or just hard code to check : 

If plank sack in inventory do not timeout.  
On pull plank sack out reset timeout and enable (not sure if plank sack has many other uses - could include additional checks that it was running previously etc)

**Comment by TheStonedTurtle** [comment]
I don't see a reason to add a config option that duplicates existing functionality, you can already set this timer to 60 minutes and if you're afking for longer than 60 minutes then idk what to tell you.
