### ISSUE TITLE
Plug-in not functioning properly after 9/25/24 update

### ISSUE THREAD

**Issue by Kharmahk** [TheStonedTurtle/Mahogany-Homes#32]
None of the functions appear to be working for me after yesterday's update. No object highlights, no arrow pointing to the next house, no session stats, and the info overlay is stuck on:

"Noella
North of East Ardougne market
All tasks completed, speak to Noella"

Even when I get new contracts, the info-box doesn't change.

I've restarted Runelite, restarted my computer, and even uninstalled and reinstalled the plugin to no avail.

**Comment by Ianbarr1** [comment]
Same here,  I've tricked it to work once by un installing and reinstalling it. No luck since. Wanted to get 99 con today but without the plugin I get Like 70k less an hour

**Comment by TheStonedTurtle** [comment]
I'm not sure what's going on for you guys but I was unable to replicate this issue, and the people I ran into while doing my testing said they were using the plugin just fine.

Do you have any additional information you can share? Such as:

Are you using the `last contract tier` option?
What contract tier are you using?
Does it break after a specific point? Is it never working?

**Comment by Kharmahk** [comment]
To clarify, after receiving the last contact (which happened to be Noella
again), I went to the house again and nothing was highlighted

**Comment by Ianbarr1** [comment]
Elite contracts as well.  I believe it might have something to to with the elites. It didn't happen when I was using teaks yesterday.

**Comment by Ianbarr1** [comment]
Also, I've noticed it's more prone to happen if you log off mid contract

**Comment by AndrewggForman** [comment]
I'm having similar issues as well, I'm doing adept contracts and was using the last-tier contract option, so I logged out and tried again with the normal contract option. That seemed to work, however, when I waited a bit and my tracker/overlay went away, I talked to Ellie in Ardougne and after she reminded me of my contract my overlay didn't return/work.

**Comment by Sudo-Rat** [comment]
I am sadly experiencing this as well, I only do expert with NPC contact. 

Tried turning off and on plugin, then full uninstall of plug-in and Rune light, did not work.

It now went from being stuck on the last task with no update, to when I reinstall the plug in, it doesn't even show in my plug-ins configuration tab anymore, but can still it remove from plugin hub.

**Comment by Thomvoort** [comment]
Having trouble too, doing elite contracts and the info display is stuck on Leela. I got it to work yesterday but I'm not sure how, either way the issue has reappeared. I will try to uninstall and clear the cache but hoping someone finds a solution.

**Comment by bedmndsn** [comment]
I was having the same issue (on Mac). It happened to me after disabling the plugin for a while and reenabling. So probably multiple client restarts and login /logout cycles with the plugin disabled might replicate the bug. I was able to fix it by trashing both the "cache" folder and "jagex cache" folders and restarting Runelite. The plugin seems to be working fine now.

**Comment by TheStonedTurtle** [comment]
Well something weird was definitely going on here, on the live version once your contract times out the plugin is broken.

When you run near a house you have a contract with it after the timeout has happened it was not re-enabling the plugin correctly. I've somehow fixed it but I really don't understand why this was happening. 

Once this PR is merged it should hopefully start working for you all again.
https://github.com/runelite/plugin-hub/pull/6668

If this does not solve the issue please let me know.

**Comment by TheStonedTurtle** [comment]
The PR has been merged and the issue seems to have been fixed. I'm going to close this issue. Please re-open or create a new one if it stops working again. Thanks everyone!
