### ISSUE TITLE
Issue with plug-in. Showing task that is not current, no highlights

### ISSUE THREAD

**Issue by JanesRS07** [TheStonedTurtle/Mahogany-Homes#33]
Hi I saw that you closed the old issue with the plugin, i am still having issues that everyone else had where my current contract is saying the same contract i had days ago and still not updating or highlighting. I've reset the client, uninstalled/reinstalled. I've tried turning on and off each option in the settings, nothing will work on my end.

![image_2024-09-28_230556875](https://github.com/user-attachments/assets/3395f4ad-e4c9-4f24-9c49-27c01614adbc)

**Comment by TheStonedTurtle** [comment]
@JanesRS07 can you add me on discord so we can troubleshoot this? I'm really confused on why this is happening and since I can't recreate it I need some help :/

**Comment by SagarChandra07** [comment]
download

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme

you may need to install the c compiler

**Comment by TheStonedTurtle** [comment]
Per our discord conversation it looks like you were somehow still running v1.7.1. After updating to v1.7.2 the problem was resolved. Closing this ticket, please feel free to open a new one if it somehow breaks again.
