### ISSUE TITLE
Add option to turn off highlights

### ISSUE THREAD

**Issue by Zacflame** [TheStonedTurtle/Mahogany-Homes#4]
I would love to see an option for this plugin to turn off the furniture highlights, but be able to keep other useful features like the current contract info, hint arrows, and the world map icon. Thank you for your contribution, regardless if this improvement comes to pass.

**Comment by TheStonedTurtle** [comment]
This feature was added in commit 8cb3a248d8467f613180875eeef2d9673dc7f8e4 and will be available once v1.2 has been merged to the plugin-hub

**Comment by TheStonedTurtle** [comment]
The update has been merged, so the plugin should automatically update next time you open the client.

Enjoy :)
