### ISSUE TITLE
Add score obtained during current session.

### ISSUE THREAD

**Issue by MxOrbulent** [TheStonedTurtle/Mahogany-Homes#7]
I leave it up to you to decide how to properly track sessions since my own coding skills are not up to par for time sensitive tasks.

Simply read what players choose (since there's 4 tiers). 

Secretly track it so people can get several ways of using it (psychology is a thing). Runescape especially with runelite is a fairly cheap game. So tracking the score regardless if the player wants it or not is no big deal.
By default, do not show the score. The majority of players in my personal opinion do better when they don't see the score (psychology). It's the same as staring at a clock, dreadfully booring. (Personally, why I am requesting this set of features is because I want that toggle so I can check the score in the current session when I want to do it).

As for what defines a session. I'd say accepting a mission and up to 5 minutes after. but you could do 10 just to be sure if the person is missing 2 arms and use their feet to play. If the player accepts another mission, the session timer essentially restarts. Otherwise if the session ends it should go inactive so java can clear score etc with garbage collect.

3 options otherwise if you want to see the score:
Toggle to show score (add a toggle button to the small widget you use when you are telling players where to go and how many tasks are left). 
Always show, not unlike those typical XP per hour stuff (and if you want to, you might even try to calculate points and xp per hour). It would display for 10 minutes or until the person starts skilling something else.

**Comment by TheStonedTurtle** [comment]
I've added a single config option that controls whether or not the session data is added to the overlay. Session data is considered the entire time the client has been open, but you can shift-right click the overlay to reset the session stats.

The session stats will display after you complete a contract and stay there until the plugin times out either manually via the shift-right click menu or automatically (which is roughly 5 minutes).
