### ISSUE TITLE
Session stats overlay always shows

### ISSUE THREAD

**Issue by benworthington** [TheStonedTurtle/Mahogany-Homes#9]
The session stats overlay never disappears. After moving on to another activity the session stats overlay is still shown. Usually, overlays will disappear after a certain amount of time not doing the activity. Therefore, I think it would be a good change to implement this feature, rather than having to manually disable the session stats overlay.

**Comment by TheStonedTurtle** [comment]
The plugin should time out after 5 minutes, including the session stats part of the overlay. If this is not happening please let me know and I'll take a deeper look at it.

In the meantime you can shift + right-click the overlay and select either the Reset or Timeout option to remove the overlay.

**Comment by benworthington** [comment]
Just checked again and the session stats still show up after an hour of doing another activity. Looks like they are not being timed out.
